name: log-ci
run-name: ${{ github.head_ref || github.ref_name }}-log-ci

on:
  pull_request:
    paths-ignore:
      - '**.org'
  workflow_dispatch:


concurrency:
  group: log-ci${{ github.event.number }}
  cancel-in-progress: true


jobs:
  unit-test:
    name: "GDUnit Tests"
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 10 # The overall timeout
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    steps:
      # checkout your repository
      - uses: actions/checkout@v4
      - uses: MikeSchulze/gdUnit4-action@v1.0.2
        with:
          godot-version: '4.2.1'
          paths: |
            res://test/
          timeout: 5
          report-name: test_report.xml
